<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../EngineeringModel.Modules.WorkItems.Application/EngineeringModel.Modules.WorkItems.Application.csproj" />
    <ProjectReference Include="../EngineeringModel.Modules.WorkItems.Domain/EngineeringModel.Modules.WorkItems.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
