<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../EngineeringModel.Modules.WorkItems.Domain/EngineeringModel.Modules.WorkItems.Domain.csproj" />
    <ProjectReference Include="../../Projects/EngineeringModel.Modules.Projects.Contracts/EngineeringModel.Modules.Projects.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/EngineeringModel.BuildingBlocks/EngineeringModel.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
